### PR TITLE
Update ratos-install.sh

### PR DESCRIPTION
**Pull request by Lino77**

### CODE REVIEW

**Review by miklschmidt — CHANGES_REQUESTED** [review]
Oof, good catch, thanks!

It would be cleaner by doing the following:
1) Rename `SRC_DIR` to `CFG_DIR` on line 7
2) Remove `BASE_DIR`, line 8
3) Replace `"$BASE_DIR"/configuration` with `"$CFG_DIR"` on lines 24 and 30.

**Comment by Lino77** [comment]
Done, and sorry for the not clean code, I can't program, I'm just trying to learn, but I'm good at comparing and analyzing.

**Comment by miklschmidt** [comment]
No worries, you're doing great, thanks for contributing! :)

**Comment by miklschmidt** [comment]
@Lino77 As you're new to this and want to learn, i thought i'd elaborate on why i said you're doing great, and what would make it even better next time:

1) ✅ Small focused PR's that addresses a specific issue
2) ✅ Correct and valid syntax (suggesting it's been tested)
3) ✅ Submitted against the development branch as requested in README.md (followed instructions)
4) ✅ Addresses important bug

Improvements:

1) Provide a title that broadly describes the change
2) Provide a description that explains why the change is needed
3) Use commit messages that describes the change you committed (this is less important to me as i usually squash the commits when merging, but is generally good practice).

That's it really, keep it up 👍 Thank you for your contribution :)

**Pull request merged**
