### PR TITLE
Update common.sh

### PR DESCRIPTION
**Pull request by Lino77**

### CODE REVIEW

**Comment by miklschmidt** [comment]
This is a binary file, not a directory `-rf` is not needed.

**Comment by Lino77** [comment]
without -f i can´t build RATOS

###### Installing RatOS CLI
sudo: unable to resolve host fv-az1778-297: Name or service not known
rm: cannot remove '/usr/local/bin/ratos': No such file or directory
++++ echo_red 'build failed, unmounting image...'
++++ echo -e -n '\e[91m'
++++ echo build failed, unmounting image...

**Comment by miklschmidt** [comment]
Ah, gotcha! @Lino77 i'll merge if you change it to `-f` instead of `-rf` :+1:

**Comment by Lino77** [comment]
changed  ;-)

**Pull request merged**
